# Build script for Travis CI
# This will automatically be run on every push to GitHub
# Build History: https://travis-ci.org/vinriviere/cross-mint-ubuntu/builds

language: c
os: linux
dist: trusty
sudo: required

before_install:
  # Install our GnuPG key pair
  - .travis/install_gpg_keys.sh
  - unset GPG_KEYS
  # Install our SSH key pair
  - .travis/install_ssh_id.sh
  - unset SSH_ID
  # Install additional packages
  - sudo apt-get install -y devscripts debhelper python-paramiko
  # Display packages versions
  - git --version
  - dpkg --version

script:
  # Set FIXED_TRAVIS_COMMIT_RANGE
  - . .travis/fix_travis_commit_range.sh
  # Fail on first error
  - set -e
  # Set DEBEMAIL variable for signing packages
  - . .travis/guess_debemail.sh
  # Deploy modified packages to https://launchpad.net/~vriviere/+archive/ubuntu/ppa
  - .travis/deploy_changed_packages.sh -m68k-atari-mint ppa:vriviere/ppa
#  - .travis/deploy_ppa_all_dists.sh binutils-m68k-atari-mint ppa:vriviere/ppa
#  - .travis/deploy_ppa_all_dists.sh mintbin-m68k-atari-mint ppa:vriviere/ppa
#  - .travis/deploy_ppa_all_dists.sh gcc-m68k-atari-mint ppa:vriviere/ppa
#  - .travis/deploy_ppa_all_dists.sh mintlib-m68k-atari-mint ppa:vriviere/ppa
#  - .travis/deploy_ppa_all_dists.sh pml-m68k-atari-mint ppa:vriviere/ppa
#  - .travis/deploy_ppa_all_dists.sh gemlib-m68k-atari-mint ppa:vriviere/ppa
#  - .travis/deploy_ppa_all_dists.sh zlib-m68k-atari-mint ppa:vriviere/ppa
#  - .travis/deploy_ppa_all_dists.sh ncurses-m68k-atari-mint ppa:vriviere/ppa
#  - .travis/deploy_ppa_all_dists.sh cflib-m68k-atari-mint ppa:vriviere/ppa
#  - .travis/deploy_ppa_all_dists.sh ldg-m68k-atari-mint ppa:vriviere/ppa
#  - .travis/deploy_ppa_all_dists.sh readline-m68k-atari-mint ppa:vriviere/ppa
#  - .travis/deploy_ppa_all_dists.sh cross-mint-essential ppa:vriviere/ppa
#  - .travis/deploy_ppa_all_dists.sh sdl-m68k-atari-mint ppa:vriviere/ppa
#  - .travis/deploy_ppa_all_dists.sh openssl-m68k-atari-mint ppa:vriviere/ppa
  # Workaround for truncated Travis CI log
  - sleep 1
